spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/nexaura
spring.datasource.username=root
spring.datasource.password=Bhushan@202005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true